### PR TITLE
Update profile scrum-16 / scrum-17 / scrum-18 / scrum-15

### PR DESCRIPTION
**Pull request by ouafaema**
- Change profile picture [SCRUM-16]
- Change profile bio [SCRUM-17]
- Change change unique link [SCRUM-18]
- change user name [SCRUM-15]

PS : The profile photo upload is working correctly but is not connected to the AWS S3 bucket

### CODE REVIEW

**Review by ouafaema — COMMENTED** [review]
changes done

**Review by sckaper — APPROVED** [review]
looks good and it works

**Comment by Fenrur** [comment]
@ouafaema There are still some parts where I don't agree, but you can merge and refactor later

**Review by Fenrur — APPROVED** [review]
@ouafaema There are still some parts where I don't agree, but you can merge and refactor later

**Pull request merged**
